# Generated by Django 3.0.1 on 2020-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Mobileno', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(default=100)),
                ('Mobileno', models.CharField(blank=True, default='100', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(default=' ', max_length=50)),
                ('Query', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forum_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=' ', max_length=100)),
                ('email', models.CharField(default='ENTER YOUR EMAILID', max_length=100)),
                ('answer', models.TextField(blank=True, max_length=2000)),
                ('answer_set', models.TextField(blank=True, default=' ', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=' ', max_length=100)),
                ('Mobileno', models.CharField(blank=True, default=' ', max_length=100)),
                ('Email', models.CharField(default=' ', max_length=100)),
                ('Profession', models.CharField(blank=True, default=' ', max_length=200)),
                ('Mentor_Img', models.ImageField(default=' ', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Primemember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobileno', models.CharField(max_length=50)),
                ('Plan', models.CharField(default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.CharField(max_length=100)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=100)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transcatid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transcation_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
